
# print(x)

# print("Handle a simple error")
# try:
#   print(x)
# except:
#   print("An error occured")

# print("Handle a simple error")
# try:
#   print(x)
# except NameError:
#   print("An error occured")
# except:
#   print("Something else went wrong")



# finally keyward example
# x=5
# try:
#   print(x)
# except :
#   print("An error occured")
# finally:
#     print("The Try concept is filled")


